
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
  - "kiali.example.com"
  gateways:
  - istio-gateway.istio-ingress.svc.cluster.local
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local # replace with your service FQDN
        port:
          number: 20001 # replace with your service port
