apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-backup-ns-webapps
  namespace: velero
spec:
  schedule: "*/10 * * * *" # this will run every 10 mins
  template:
    includedNamespaces:
    - 'webapps'
    excludedNamespaces:
    includedResources:
    - '*'
    excludedResources:
    - storageclasses.storage.k8s.io
    includeClusterResources: null
    snapshotVolumes: true
    storageLocation: default
    volumeSnapshotLocations:
      - default