apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-backup-ns-default
  namespace: velero
spec:
#   schedule: 0 * * * * # this will run every hour
  schedule: "*/10 * * * *" # this will run every 10 mins
  template:
    includedNamespaces:
    - 'default'
    excludedNamespaces:
    includedResources:
    - '*'
    excludedResources:
    - storageclasses.storage.k8s.io
    includeClusterResources: null
    snapshotVolumes: true
    storageLocation: default
    volumeSnapshotLocations:
      - default