apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-svc
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.port }}
      name: http


---


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appname }}-vs
spec:
  hosts:
  - "{{ .Values.appname }}.example.com"
  gateways:
  - istio-gateway # Name of the gateway created in the previous step
  http:
  - route:
    - destination:
        host: {{ .Values.appname }}-svc # replace with your service FQDN
        port:
          number: 80 # replace with your service port