apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-argo-apps
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-apps
    repoURL: 'https://github.com/rohitkamle/argo-cd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true