apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/instance: app-of-apps
  name: k8_config
  namespace: argo
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: k8_config
    repoURL: 'https://github.com/rohitkamle/argo-cd'
    targetRevision: HEAD
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true