apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/instance: app-of-apps
  name: webapp2
  namespace: argo
spec:
  destination:
    name: in-cluster
    namespace: webapps
  source:
    helm:
      valueFiles:
        - values.yaml
    path: apps/webapp2/helm-charts
    repoURL: 'https://github.com/rohitkamle/argo-cd'
    targetRevision: HEAD
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true