apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp2
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: webapps
  source:
    path: apps/webapp2/helm-charts
    repoURL: 'https://github.com/rohitkamle/argo-cd'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
