
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-vs
  namespace: istio-system
spec:
  hosts:
  - "argo.example.com"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: argo-cd-argocd-server.argo.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: argo-cd-argocd-server.argo.svc.cluster.local
        port:
          number: 443
      weight: 100
    route:
    - destination:
        host: argo-cd-argocd-server.argo.svc.cluster.local
        port:
          number: 80
      weight: 0
